apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: spin-rust
resources:
  - ../../../base/spin
nameSuffix: -rust
commonAnnotations:
  func-lang: rust
commonLabels:
  app: spin-rust
images:
- name: spin
  newName: spin-rust