apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: azfn-js
resources:
  - ../../../base/azfn
nameSuffix: -js
commonAnnotations:
  func-lang: js
commonLabels:
  app: azfn-js
images:
- name: azfn
  newName: azfn-js