apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: azfn-js
resources:
  - ../../../base/azfn
nameSuffix: -js
commonAnnotations:
  func-lang: js
commonLabels:
  app: az-func-js
images:
- name: az-func
  newName: az-func-js