spin_manifest_version = 2

[application]
authors = ["Justin Pflueger <justin.pflueger@fermyon.com>"]
description = ""
name = "spin-func-js"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "spin-func-js"

[component.spin-func-js]
source = "target/spin-func-js.wasm"
exclude_files = ["**/node_modules"]
[component.spin-func-js.build]
command = "npm run build"
