spin_manifest_version = "1"
authors = ["Justin Pflueger <justin.pflueger@fermyon.com>"]
description = "Spin function written in JavaScript"
name = "spin-func-js"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-func-js"
source = "target/spin-func-js.wasm"
exclude_files = ["**/node_modules"]
[component.trigger]
route = "/json"
[component.build]
command = "npm run build"
