apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: spin-py
resources:
  - ../../../base/spin
nameSuffix: -py
commonAnnotations:
  func-lang: py
commonLabels:
  app: spin-func-py
images:
- name: spin-func
  newName: spin-func-py