apiVersion: apps/v1
kind: Deployment
metadata:
  name: azfn
spec:
  template:
    spec:
      containers:
        - name: azfn
          image: azfn:latest
          ports:
            - containerPort: 80
              name: http
      nodeSelector:
        func-runtime: azfn