apiVersion: apps/v1
kind: Deployment
metadata:
  name: azfn-func
spec:
  template:
    spec:
      containers:
        - name: azfn-func
          image: azfn-func:latest
          ports:
            - containerPort: 80
              name: http
      tolerations:
      - key: func-runtime
        operator: Equal
        value: azfn
        effect: NoSchedule
