apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-func
spec:
  template:
    spec:
      containers:
        - name: az-func
          image: az-func:latest
          ports:
            - containerPort: 80
              name: http
      nodeSelector:
        func-runtime: azfn
