apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: azfn-py
resources:
  - ../../../base/azfn
nameSuffix: -py
commonAnnotations:
  func-lang: py
commonLabels:
  app: az-func-py
images:
- name: az-func
  newName: az-func-py