apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: spin-js
resources:
  - ../../../base/spin
nameSuffix: -js
commonAnnotations:
  func-lang: js
commonLabels:
  app: spin-func-js
images:
- name: spin-func
  newName: spin-func-js