apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-func
spec:
  template:
    spec:
      runtimeClassName: wasmtime-spin-v1
      containers:
        - name: spin-func
          image: spin-func:latest
          ports:
            - containerPort: 80
              name: http
      nodeSelector:
        func-runtime: spin