spin_manifest_version = 2

[application]
name = "spin-func-go"
version = "0.1.0"
authors = ["Justin Pflueger <justin.pflueger@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "spin-func-go"

[component.spin-func-go]
source = "main.wasm"
allowed_outbound_hosts = []
[component.spin-func-go.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
