apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: spin-cs
resources:
  - ../../../base/spin
nameSuffix: -cs
commonAnnotations:
  func-lang: cs
commonLabels:
  app: spin-func-cs
images:
- name: spin-func
  newName: spin-func-cs