apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: azfn

resources:
  # - ./cs
  - ./js
  - ./py

images:
# - name: az-func-cs
#   newName: jpflueger/az-func-cs
- name: az-func-js
  newName: jpflueger/az-func-js
- name: az-func-py
  newName: jpflueger/az-func-py
