apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: azfn

resources:
  - js
  - py

images:
- name: azfn-js
  newName: jpflueger/azfn-js
  newTag: 67314bc
- name: azfn-py
  newName: jpflueger/azfn-py
  newTag: 67314bc
