apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: spin-go
resources:
  - ../../../base/spin
nameSuffix: -go
commonAnnotations:
  func-lang: go
commonLabels:
  app: spin-go
images:
- name: spin
  newName: spin-go