spin_manifest_version = 2

[application]
authors = ["Justin Pflueger <justin.pflueger@fermyon.com>"]
description = ""
name = "spin-func-py"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "spin-func-py"

[component.spin-func-py]
source = "app.wasm"
[component.spin-func-py.build]
command = "spin py2wasm app -o app.wasm"
watch = ["app.py", "Pipfile"]
