apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: spin

resources:
  - js
  - py
  - rust
  - go

images:
- name: spin-js
  newName: jpflueger/spin-js
  newTag: 9a920ff
- name: spin-py
  newName: jpflueger/spin-py
  newTag: 9a920ff
- name: spin-rust
  newName: jpflueger/spin-rust
  newTag: 9a920ff
- name: spin-go
  newName: jpflueger/spin-go
  newTag: 9a920ff