apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: spin

resources:
  - js
  - py

images:
- name: spin-func-js
  newName: jpflueger/spin-func-js
- name: spin-func-py
  newName: jpflueger/spin-func-py
