apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: spin

resources:
- js
- py
- rust
- go

images:
- name: spin-go
  newName: docker.io/jpflueger/spin-go
  newTag: 9a920ff
- name: spin-js
  newName: docker.io/jpflueger/spin-js
  newTag: 9a920ff
- name: spin-py
  newName: docker.io/jpflueger/spin-py
  newTag: 9a920ff
- name: spin-rust
  newName: docker.io/jpflueger/spin-rust
  newTag: 9a920ff
